config/routes.rb
Rails.application.routes.draw do
  resources :tasks, only: [:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tasks#index'
  get 'result', to: 'tasks#result'
  get 'authorization', to: 'authorization#index'
  post 'authorization', to: 'authorization#authorization'
  post 'exit', to: 'authorization#exit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authorization_controller.rb
class AuthorizationController < ApplicationController

  def index

  end

  def authorization
    uri = URI('http://localhost:3000/authenticate')
    answer = Net::HTTP.post(uri, auth_params.to_query)
    result = JSON.parse(answer.body)
    if result['error']
      redirect_to authorization_path, notice: 'Ошибка авторизации! Проверьте д'\
'анные и повторите попытку!'
    else
      session[:auth_token] = result['auth_token']
      redirect_to root_path
    end
  end

  def exit
    session[:auth_token] = nil
    redirect_to root_path
  end

  private

  def auth_params
    params.permit(:email, :password).to_h
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index; end

  def create
    header = { auth_token: session[:auth_token] }
    uri = URI('http://localhost:3000/tasks')
    json_answer = Net::HTTP.post(uri, task_params.to_query, header)
    answer = JSON.parse(json_answer.body)
    if answer['error'] == 'Not Authorized'
      redirect_to authorization_path
    else
      @message = if answer['error'] == 'Invalid parameters'
                   'Ошибка ввода параметров!'
                 else
                   result = answer['result']
                   case result.size
                   when 1
                     format('Ответ: x = %.3f', result[0])
                   when 2
                     format('Ответ: x1 = %.3f, x2 = %.3f',
                            result[0], result[1])
                   else
                     'Данное уравнение не имеет решений!'
                   end
                 end
      render 'result'
    end
  end

  private

  def task_params
    params.permit(:a, :b, :c, :d).to_h
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/authorization/index.html.erb
<div class="login-wrap">
  <div class="login-html">
    <input id="tab-1" type="radio" name="tab" class="sign-in" checked>
    <label for="tab-1" class="tab">Авторизация</label>
    <input id="tab-2" type="radio" name="tab" class="sign-up">
    <label for="tab-2" class="tab"></label>
    <div class="login-form">
      <div class="sign-in-htm">
        <%= form_tag do %>
            <div class="group">
              <label for="user" class="label">Email</label>
              <%= email_field_tag :email, nil, class: 'input' %>
            </div>
            <div class="group">
              <label for="pass" class="label">Пароль</label>
              <%= password_field_tag :password, nil, class: 'input' %>
            </div>
            <div class="group">
              <%= submit_tag 'Вход', class: 'button'  %>
            </div>
            <div class="group">
            <% flash.each do |key, message| %>
                <p class="<%= key %>"><%= message %></p>
            <% end %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MathSystem</title>
  <%= csrf_meta_tags %>
  <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/tasks/index.html.erb
<div class="login-wrap">
  <div class="login-html">
    <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Линейное</label>
    <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Квадратное</label>
    <div class="login-form">
      <div class="sign-in-htm">
        <%= form_tag do %>
            <div class="group">
              <%= text_field_tag :a, nil, class: 'input2', pattern: '-?\d+(\.\d+)?', value: 0 %><p>x +</p>
              <%= text_field_tag :b, nil, class: 'input2', pattern: '-?\d+(\.\d+)?', value: 0 %><p>=</p>
              <%= text_field_tag :c, nil, class: 'input2', pattern: '-?\d+(\.\d+)?', value: 0 %>
            </div>
            <div class="group">
              <%= submit_tag 'Решить', class: 'button'  %>
            </div>
        <% end %>
        <% if session[:auth_token] %>
            <div class="group">
              <%= button_to 'Выход', exit_path, class: 'button' %>
            </div>
        <% end %>
      </div>
      <div class="sign-up-htm">
        <%= form_tag do %>
            <div class="group">
              <%= text_field_tag :a, nil, class: 'input2', pattern: '-?\d+(\.\d+)?', value: 0 %><p>x<sup>2</sup> +</p>
              <%= text_field_tag :b, nil, class: 'input2', pattern: '-?\d+(\.\d+)?', value: 0 %><p>x +</p>
              <%= text_field_tag :c, nil, class: 'input2', pattern: '-?\d+(\.\d+)?', value: 0 %><p>=</p>
              <%= text_field_tag :d, nil, class: 'input2', pattern: '-?\d+(\.\d+)?', value: 0 %>
            </div>
            <div class="group">
              <%= submit_tag 'Решить', class: 'button'  %>
            </div>
        <% end %>
        <% if session[:auth_token] %>
            <div class="group">
              <%= button_to 'Выход', exit_path, class: 'button' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--</html>-->

app/views/tasks/result.html.erb
<div class="login-wrap">
  <div class="login-html">
    <input id="tab-1" type="radio" name="tab" class="sign-in" checked>
    <label for="tab-1" class="tab">Результаты</label>
    <input id="tab-2" type="radio" name="tab" class="sign-up">
    <label for="tab-2" class="tab"></label>
    <div class="login-form">
      <div class="sign-in-htm">
        <%= form_tag do %>
            <% if params[:d]%>
                <div class="group">
                  <p>
                    <%= params[:a] %>x<sup>2</sup> + <%= params[:b] %>x +
                    <%= params[:c] %> = <%= params[:d] %>
                  </p>
                </div>
            <% else %>
                <div class="group">
                  <p><%= params[:a] %>x + <%= params[:b] %> = <%= params[:c] %></p>
                </div>
            <% end %>
            <div class="group">
              <p><%= @message %></p>
            </div>
            <div class="group">
              <%= link_to 'Назад', tasks_path, class: 'button' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>